version: '3.9'

services:
  postgres:
    container_name: seti_db
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seti_db
    networks:
      - seti


  app:
    container_name: prueba-seti
    image: seti:v1
    build: ./deployment/
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/seti_db
      SPRING_R2DBC_USERNAME: postgres
      SPRING_R2DBC_PASSWORD: root
      SPRING_SQL_INIT_MODE: always

    networks:
      - seti

networks:
  seti:
    driver: bridge
